---
title: "Lab 6 report"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{lab_report_knapsack}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(Khwarizmi)
```


# Introduction

In this lab report the time for different algorithms for solving the Knapsack problem will be investigated.

# Knapsack data

Here we generate the data that will be used for testing the different algorithms.

```{r}
RNGversion(min(as.character(getRversion()),"3.5.3"))

##old sampler used for backward compatibility
## suppressWarnings() can be used so that the above warning is not displayed
set.seed(42, kind = "Mersenne-Twister", normal.kind = "Inversion")
n <- 1000000
knapsack_objects <-
data.frame(
w=sample(1:4000, size = n, replace = TRUE),
v=runif(n = n, 0, 10000)
)
```

# Brute force search

```{r}
system.time(bfk <- brute_force_knapsack(x = knapsack_objects[1:16,], W = 2000))
```


# Dynamic programming

```{r}
system.time(bfk <- knapsack_dynamic(x = knapsack_objects[1:500,], W = 20))
```


# Greedy heuristic

```{r}
system.time(bfk <- greedy_knapsack(x = knapsack_objects[1:1000000,], W = 2000))
```

